const mockData = {
  models: [
    {
      id: "gpt-5-mini",
      label: "GPT-5 mini",
      tier: "premium",
      blurb: "Melhor equilíbrio: ótimo texto, fala fluida e conformidade limpa. Recomendado.",
      badge: "Premium"
    },
    {
      id: "gemini-flash",
      label: "Gemini 3.5 Flash",
      tier: "premium",
      blurb: "Rápido e versátil, com rotação de chaves e fallback de modelo.",
      badge: "Premium"
    },
    {
      id: "deepseek",
      label: "DeepSeek V4",
      tier: "free",
      blurb: "Gratuito. Bom roteiro, com checagem de conformidade reforçada.",
      badge: "Free"
    }
  ],
  defaults: {
    free: "deepseek",
    paid: "deepseek"
  },
  presets: {
    martelete: {
      productName: "MARTELETE ROTATIVO ROMPEDOR 800W 8 PEÇAS",
      slides: [
        {
          section: "ABERTURA",
          headline: "Gancho Psicológico de Impacto",
          pitch: "Olha essa oportunidade que chegou agora. O preço é exclusivo enquanto a live tá no ar. Clica no botão de comprar e garante o seu.",
          pitch_urgente: "ATENÇÃO! Para tudo o que está fazendo e olha para esta tela agora mesmo! O estoque tá acabando rápido e a live tá voando!",
          pitch_persuasivo: "Se você quer economizar tempo e fazer um serviço profissional sem esforço, essa é a ferramenta lógica para o seu dia a dia.",
          pitch_story: "Muitos clientes me diziam que passavam dias sofrendo com furadeira fraca, até que conheceram a facilidade deste martelete.",
          pitch_descontraido: "E aí galera! Olha que massa isso aqui. Sabe aquela reforma que tá travada há meses? Bora resolver isso agora de boa!",
          role: "promessa",
          visual_focus: "geral"
        },
        {
          section: "CENA",
          headline: "Apresentação do Problema (Dor)",
          pitch: "Cansou de furar parede com furadeira fraca? Aquela reforma que nunca sai do papel. Agora você vai romper concreto sem sofrer.",
          pitch_urgente: "RÁPIDO! Furadeiras comuns quebram e travam, te fazendo perder tempo e passar raiva no meio do serviço!",
          pitch_persuasivo: "O custo de comprar ferramentas baratas e fracas é ter que refazer o trabalho e se estressar toda vez.",
          pitch_story: "Eu mesmo já passei horas tentando furar uma coluna em casa e só gastei broca à toa, até que usei esse rompedor.",
          pitch_descontraido: "Quem nunca comprou aquela furadeira barata e ela começou a sair fumaça na primeira semana? Fala sério!",
          role: "dor",
          visual_focus: "geral"
        },
        {
          section: "COMPATIBILIDADE · VOLTAGEM",
          headline: "Especificação e voltagem",
          pitch: "Ele funciona em tomada comum. Verifica a voltagem da sua casa antes de comprar. Assim você garante que vai usar sem problema.",
          pitch_urgente: "CORRE! Escolha a voltagem certa agora no carrinho para não perder o lote promocional da live!",
          pitch_persuasivo: "Sempre certifique-se de escolher a voltagem adequada (110V ou 220V) para garantir a eficiência máxima do motor.",
          pitch_story: "Enviamos o modelo correto direto para a sua casa, embalado e pronto para o primeiro uso logo após abrir.",
          pitch_descontraido: "Fica ligado na voltagem da tua casa antes de fechar o pedido, beleza? Pra não ter erro na hora de ligar na tomada.",
          role: "espec",
          visual_focus: "geral"
        },
        {
          section: "SPEC · POTÊNCIA",
          headline: "Diferencial de Potência",
          pitch: "São 800 watts de potência real. Isso significa mais força pra furar. Você acaba o serviço muito mais rápido.",
          pitch_urgente: "FORÇA TOTAL! São 800W destruidores de concreto! Você não vai achar nada parecido por esse preço!",
          pitch_persuasivo: "Os 800W de potência nominal garantem o torque ideal para perfurações de alta densidade sem sobrecarga.",
          pitch_story: "Nosso teste prático mostrou que ele perfura vigas de concreto em menos de 10 segundos sem esforço.",
          pitch_descontraido: "O bicho tem 800W de potência real, bruto demais! Passa no concreto que nem manteiga, você vai ver.",
          role: "prova",
          visual_focus: "geral"
        },
        {
          section: "SPEC · ROTAÇÃO",
          headline: "Rotação e Torque",
          pitch: "Ele tem rotação de até 2800 RPM. A furadeira não trava no material duro. Vai reto, sem perder tempo.",
          pitch_urgente: "VELOCIDADE MÁXIMA! Até 2800 rotações por minuto! Fura qualquer estrutura num piscar de olhos!",
          pitch_persuasivo: "A alta taxa de 2800 RPM reduz o atrito e preserva a via útil das brocas de vídea.",
          pitch_story: "Eu fiz o teste com tijolo baiano e concreto armado: a rotação se mantém firme e não cai.",
          pitch_descontraido: "Ele gira a até 2800 RPM, então não fica engasgando nem travando quando pega pedra no caminho.",
          role: "espec",
          visual_focus: "geral"
        },
        {
          section: "CTA",
          headline: "Chamada de Ação Final",
          pitch: "Se você quer um martelete potente, é esse. Clica agora e escolhe a sua voltagem. Não deixa passar, porque o preço é de live.",
          pitch_urgente: "ÚLTIMOS MINUTOS! O estoque da live tá acabando! Clica no carrinho laranja agora e garante o seu antes que mude o preço!",
          pitch_persuasivo: "Faça um investimento inteligente na sua produtividade e pare de alugar ferramentas. Clique e compre com frete grátis.",
          pitch_story: "Todos que compraram na live passada voltaram para agradecer a facilidade e a rapidez da entrega.",
          pitch_descontraido: "Não marca bobeira não, clica ali no carrinho laranja, escolhe a voltagem e garante o seu pra começar a usar essa semana!",
          role: "cta",
          visual_focus: "produto_fixado"
        }
      ]
    },
    cinta: {
      productName: "Short Cinta Modeladora Masculina Bermuda de Compressão Plus Size",
      slides: [
        {
          section: "ABERTURA",
          headline: "Gancho Psicológico de Impacto",
          pitch: "Olha a diferença imediata na postura e na silhueta. Esse short modelador chegou para redefinir o conforto e a autoimagem masculina.",
          pitch_urgente: "ATENÇÃO! Se você quer melhorar sua postura e reduzir medidas de forma instantânea, preste atenção neste produto agora!",
          pitch_persuasivo: "Estudos mostram que uma postura alinhada aumenta a confiança e previne dores lombares. Este shapewear é a solução perfeita.",
          pitch_story: "Eu usava camisas que ficavam marcadas e me sentia desconfortável, até que comecei a usar essa bermuda por baixo.",
          pitch_descontraido: "E aí, galera! Sabe aquela camisa social que tá meio apertada? Olha o segredo pra deixar ela certinha no corpo de forma leve.",
          role: "promessa",
          visual_focus: "geral"
        },
        {
          section: "CENA",
          headline: "Problema e Dor",
          pitch: "Cansado daquela sensação de roupa apertada ou de dores nas costas ao final do dia? Roupas comuns não dão o suporte que seu corpo precisa.",
          pitch_urgente: "AGORA! Pare de sofrer tentando esconder a barriga ou curvando as costas! Resolva isso em segundos!",
          pitch_persuasivo: "A falta de compressão abdominal adequada sobrecarrega a coluna lombar durante o dia de trabalho.",
          pitch_story: "Um cliente nosso sofria com dores ao ficar sentado no escritório por horas, até testar essa bermuda de compressão.",
          pitch_descontraido: "Ninguém merece ficar ajeitando a calça ou se sentindo incomodado em festa ou no trabalho, né?",
          role: "dor",
          visual_focus: "geral"
        },
        {
          section: "ARGUMENTO DE VENDA",
          headline: "Diferenciais e Tecnologia",
          pitch: "Tecido respirável de alta elasticidade com costuras invisíveis que não marcam na roupa. Suporte abdominal e correção postural integrados.",
          pitch_urgente: "EXCLUSIVO! Cinta com tecnologia shapewear alemã que não enrola na cintura e mantém a ventilação livre de suor!",
          pitch_persuasivo: "A compressão graduada estimula a circulação e oferece suporte anatômico sem restringir os movimentos diários.",
          pitch_story: "Desenvolvemos esse tecido em poliéster e elastano premium para garantir que ele dure centenas de lavagens sem ceder.",
          pitch_descontraido: "O tecido é super fresco, não aperta demais a ponto de faltar ar e você nem percebe que tá usando.",
          role: "prova",
          visual_focus: "geral"
        },
        {
          section: "CTA",
          headline: "Chamada para Ação",
          pitch: "Escolha seu tamanho na tabela e clique em comprar. A promoção com frete reduzido é válida somente durante a live.",
          pitch_urgente: "ESTOQUE LIMITADO! As unidades Plus Size estão voando! Toque no botão laranja abaixo e garanta a sua agora!",
          pitch_persuasivo: "Adquira agora a bermuda shapewear e eleve seu conforto diário. Garantia de devolução em 7 dias sem burocracia.",
          pitch_story: "Quem comprou o kit com 3 unidades garantiu o uso diário e aprovou 100% o resultado.",
          pitch_descontraido: "Bora garantir o seu? Clica no carrinho aqui do lado, escolhe o tamanho ideal e aproveita o desconto de hoje!",
          role: "cta",
          visual_focus: "produto_fixado"
        }
      ]
    }
  },
  // --- TIKTOK SHOP OS ENTERPRISE DATA ENGINE ---
  executiveMetrics: {
    healthScore: 96,
    healthStatus: "Excelente",
    healthAlerts: ["Otimização de horário recomendada às 19h30", "3 produtos elegíveis para amostras grátis"],
    kpis: {
      revenueToday: { label: "Receita Hoje", value: 14890.50, change: "+24.8%", isUp: true, sparkline: [40, 55, 75, 60, 95, 110, 148] },
      revenueYesterday: { label: "Receita Ontem", value: 11930.20, change: "+12.1%", isUp: true, sparkline: [30, 45, 60, 55, 80, 100, 119] },
      revenue7d: { label: "Receita Últimos 7 Dias", value: 87450.00, change: "+31.4%", isUp: true, sparkline: [10, 12, 11, 13, 14, 15, 17] },
      revenue30d: { label: "Receita Últimos 30 Dias", value: 342180.00, change: "+45.2%", isUp: true, sparkline: [25, 28, 30, 32, 35, 38, 45] },
      netProfit: { label: "Lucro Líquido Estimado", value: 119760.00, change: "+38.0%", isUp: true, sparkline: [8, 9, 10, 11, 12, 13, 15] },
      totalCommission: { label: "Comissão de Afiliado", value: 68436.00, change: "+42.5%", isUp: true, sparkline: [5, 6, 7, 7, 8, 9, 10] },
      ticketMedio: { label: "Ticket Médio", value: 114.80, change: "+4.2%", isUp: true, sparkline: [100, 105, 108, 110, 112, 114, 115] },
      conversionRate: { label: "Taxa de Conversão", value: 4.8, change: "+1.2%", isUp: true, isPercent: true, sparkline: [3.2, 3.5, 3.8, 4.0, 4.2, 4.5, 4.8] },
      roas: { label: "ROAS Médio", value: 4.2, change: "+0.8x", isUp: true, sparkline: [3.1, 3.4, 3.6, 3.8, 4.0, 4.1, 4.2] },
      cpa: { label: "CPA Médio", value: 18.50, change: "-14.2%", isUp: true, sparkline: [24, 23, 22, 21, 20, 19, 18] },
      cpm: { label: "CPM Médio", value: 12.40, change: "-8.5%", isUp: true, sparkline: [15, 14, 14, 13, 13, 12, 12] },
      ctr: { label: "CTR das Lives", value: 8.9, change: "+2.1%", isUp: true, isPercent: true, sparkline: [6.1, 6.5, 7.0, 7.5, 8.0, 8.5, 8.9] },
      totalOrders: { label: "Pedidos Realizados", value: 2980, change: "+18.4%", isUp: true, isRawNumber: true, sparkline: [200, 220, 250, 270, 280, 290, 298] },
      unitsSold: { label: "Produtos Vendidos", value: 3410, change: "+22.0%", isUp: true, isRawNumber: true, sparkline: [220, 240, 270, 290, 310, 330, 341] }
    }
  },

  liveStudioState: {
    isLiveActive: true,
    durationSeconds: 4320, // 1h 12m
    currentViewers: 1840,
    peakViewers: 2450,
    likesCount: 48200,
    commentsCount: 3120,
    ordersCount: 284,
    revenueTotal: 29480.00,
    conversionRate: 5.4,
    ticketMedio: 103.80,
    pinnedProduct: "Base Líquida WePink Matte",
    salesPerMinute: 4.2,
    revenuePerMinute: 436.00,
    aiCopilotPrompts: [
      { id: 1, type: "urgent", text: "🔥 Alta retenção agora! Repita o gancho de Frete Grátis nos próximos 30s.", action: "Acionar Cupom" },
      { id: 2, type: "opportunity", text: "📈 A taxa de conversão da Base WePink subiu para 6.2%. Mantenha o produto fixado.", action: "Manter Fixado" },
      { id: 3, type: "recommendation", text: "⚡ Sugestão de IA: A audiência está perguntando de tom de pele. Mostre o swatch na mão.", action: "Ver Roteiro Swatch" }
    ]
  },

  sampleCampaigns: [
    {
      id: "samp_wepink",
      brand: "WePink Official",
      productName: "Base Líquida WePink Matte 45ml",
      category: "Maquiagem",
      minFollowers: 1000,
      approvalRate: 94,
      productValue: 99.90,
      commissionPercent: 20,
      image: "https://s.500fd.com/tt_product/b5e487422d45496eaf883b32fafbe07b~tplv-aphluv4xwc-crop-webp:1500:1500.webp",
      requirements: "Mínimo 1 Live por semana ou 2 Vídeos no feed",
      aiRequestPrompt: "Olá equipe WePink! Sou criador focado em maquiagem no TikTok Shop com alta engajamento. Gostaria de receber a amostra da Base Matte para apresentar na minha live das 19h onde atinjo pico de 1.800 espectadores."
    },
    {
      id: "samp_lenovo",
      brand: "Lenovo Audio BR",
      productName: "Fone Bluetooth GM2 Pro Gamer",
      category: "Eletrônicos",
      minFollowers: 500,
      approvalRate: 88,
      productValue: 49.90,
      commissionPercent: 15,
      image: "https://s.500fd.com/tt_product/3e0f119bd363459386d988fd71cae4bb~tplv-aphluv4xwc-resize-jpeg:330:330.jpeg",
      requirements: "Vídeo unboxing ou demonstração em live gamer",
      aiRequestPrompt: "Olá time Lenovo! Realizo lives diárias de eletrônicos no TikTok Shop com média de 2.000 espectadores por transmissão. Solicito o envio do GM2 Pro para demonstração ao vivo de baixa latência."
    },
    {
      id: "samp_principia",
      brand: "Principia Skincare",
      productName: "Sérum Retinol 0,3% + Ácido Hialurônico",
      category: "Skincare",
      minFollowers: 2000,
      approvalRate: 91,
      productValue: 54.00,
      commissionPercent: 22,
      image: "https://s.500fd.com/tt_product/40644a40741b42b3a58af1e641612b3b~tplv-aphluv4xwc-resize-webp:800:800.webp",
      requirements: "Avaliação sincera de textura e rotina em vídeo de 30s",
      aiRequestPrompt: "Olá Principia! Meu público de skincare busca produtos de alta eficácia comprovada. Gostaria de solicitar a amostra do Sérum Retinol 0.3% para testar a aplicação na live e gerar vendas imediatas."
    }
  ],

  aiStrategicInsights: [
    {
      id: "insight-1",
      title: "Pico de Conversão no Horário das 19h",
      what: "Nas últimas 24h, a receita teve um pico de 42% entre 19:00 e 21:30.",
      why: "Sua audiência do TikTok Shop é majoritariamente trabalhadora e acessa o app ao chegar em casa.",
      action: "Agendar as lives principais com 30 minutos de antecedência (às 18:30) para capturar o aquecimento do tráfego.",
      expectedImpact: "+R$ 4.200,00 no faturamento diário estimado."
    },
    {
      id: "insight-2",
      title: "Oportunidade em Produtos de Ticket Médio R$ 49-79",
      what: "Produtos abaixo de R$ 80,00 estão com taxa de conversão 2.4x superior aos itens acima de R$ 150,00.",
      why: "Compradores de impulso no TikTok fecham pedidos de baixo valor sem pesquisar concorrência.",
      action: "Iniciar a live com itens de entrada (Mini Processador USB e Fone Lenovo) antes de apresentar a Base WePink.",
      expectedImpact: "Aumento de 35% no volume total de pedidos da transmissão."
    }
  ],

  aiFeedItems: [
    { id: 1, type: "sale", title: "🎉 Meta do Dia Atingida!", time: "Há 12 min", desc: "Você ultrapassou R$ 14.000,00 em vendas brutas hoje." },
    { id: 2, type: "viral", title: "🔥 Produto em Tendência Viral", time: "Há 45 min", desc: "A Base WePink subiu 42.8% em buscas de afiliados nesta hora." },
    { id: 3, type: "ai", title: "🤖 Recomendação IA Disponível", time: "Há 1h", desc: "A IA encontrou 3 novas campanhas de produtos gratuitos com 94% de aprovação." }
  ],

  extensionStatus: {
    isConnected: true,
    version: "2.4.1",
    lastSync: "Agora (WS Conectado)",
    autoPinEnabled: true,
    autoCouponEnabled: true,
    features: [
      "Fixação Automática de Sacola em Live",
      "Sincronização em Tempo Real com TikTok Seller Center",
      "Alertas de Mudança de Conversão na Tela",
      "Extrator de Produtos Vencedores em 1 Clique"
    ]
  },

  products: [
    {
      id: "base_wepink_virginia",
      title: "Base Líquida WePink Matte Alta Cobertura Resistente à Água - Virginia Fonseca 45ml",
      livesCount: 142,
      rate: 38,
      sales: 12450,
      gmv: "R$ 498.000",
      category: "Maquiagem & Beleza",
      competition: "Alta",
      competitionColor: "#e0685f",
      margin: "R$ 3.500,00 / live",
      image: "https://s.500fd.com/tt_product/b5e487422d45496eaf883b32fafbe07b~tplv-aphluv4xwc-crop-webp:1500:1500.webp",
      salesToday: 412,
      salesYesterday: 385,
      weeklyGrowth: 42.8,
      creatorsCount: 142,
      commissionPercent: 20,
      commissionVal: 19.98,
      profitPotential: 99600.00,
      trendStatus: "alta",
      scoreBreakdown: { demanda: 9.8, crescimento: 9.5, margem: 9.2, saturacao: 6.0, escalabilidade: 9.6 }
    },
    {
      id: "fone_lenovo_gm2_pro",
      title: "Fone de Ouvido Bluetooth TWS Gamer Lenovo GM2 Pro Sem Fio HD Mic Low Latency",
      livesCount: 98,
      rate: 31,
      sales: 8920,
      gmv: "R$ 312.200",
      category: "Eletrônicos & Áudio",
      competition: "Média",
      competitionColor: "#8e8e8e",
      margin: "R$ 2.180,00 / live",
      image: "https://s.500fd.com/tt_product/3e0f119bd363459386d988fd71cae4bb~tplv-aphluv4xwc-resize-jpeg:330:330.jpeg",
      salesToday: 295,
      salesYesterday: 270,
      weeklyGrowth: 35.2,
      creatorsCount: 98,
      commissionPercent: 15,
      commissionVal: 7.35,
      profitPotential: 46830.00,
      trendStatus: "alta",
      scoreBreakdown: { demanda: 9.5, crescimento: 9.0, margem: 8.5, saturacao: 5.2, escalabilidade: 9.2 }
    },
    {
      id: "mini_processador_usb",
      title: "Mini Processador Elétrico de Alimentos USB Triturador de Alho e Temperos 250ml",
      livesCount: 76,
      rate: 28,
      sales: 6410,
      gmv: "R$ 153.840",
      category: "Cozinha & Casa",
      competition: "Média",
      competitionColor: "#8e8e8e",
      margin: "R$ 1.420,00 / live",
      image: "https://s.500fd.com/tt_product/b5e487422d45496eaf883b32fafbe07b~tplv-aphluv4xwc-crop-webp:1500:1500.webp",
      salesToday: 198,
      salesYesterday: 175,
      weeklyGrowth: 28.4,
      creatorsCount: 76,
      commissionPercent: 18,
      commissionVal: 4.32,
      profitPotential: 27691.20,
      trendStatus: "alta",
      scoreBreakdown: { demanda: 8.9, crescimento: 8.8, margem: 8.7, saturacao: 4.5, escalabilidade: 8.9 }
    },
    {
      id: "serum_principia_retinol",
      title: "Sérum Facial Principia Retinol 0,3% + Ácido Hialurônico Anti-Idade 30ml",
      livesCount: 64,
      rate: 34,
      sales: 5230,
      gmv: "R$ 282.420",
      category: "Skincare & Beleza",
      competition: "Baixa",
      competitionColor: "#5cc978",
      margin: "R$ 2.850,00 / live",
      image: "https://s.500fd.com/tt_product/40644a40741b42b3a58af1e641612b3b~tplv-aphluv4xwc-resize-webp:800:800.webp",
      salesToday: 165,
      salesYesterday: 150,
      weeklyGrowth: 38.6,
      creatorsCount: 64,
      commissionPercent: 22,
      commissionVal: 11.88,
      profitPotential: 62132.40,
      trendStatus: "alta",
      scoreBreakdown: { demanda: 9.2, crescimento: 9.4, margem: 9.5, saturacao: 3.8, escalabilidade: 9.3 }
    },
    {
      id: "escova_alisadora_3em1",
      title: "Escova Alisadora Bivolt 3 em 1 Hair Straightener Brush com Íons Negativos",
      livesCount: 88,
      rate: 29,
      sales: 7850,
      gmv: "R$ 384.650",
      category: "Beleza & Cabelo",
      competition: "Alta",
      competitionColor: "#e0685f",
      margin: "R$ 2.940,00 / live",
      image: "https://s.500fd.com/tt_product/78d55bd9b4bf43a4910a857206b59b98~tplv-aphluv4xwc-crop-webp:1024:1024.webp",
      salesToday: 245,
      salesYesterday: 230,
      weeklyGrowth: 31.0,
      creatorsCount: 88,
      commissionPercent: 16,
      commissionVal: 7.84,
      profitPotential: 61544.00,
      trendStatus: "alta",
      scoreBreakdown: { demanda: 9.4, crescimento: 8.9, margem: 8.8, saturacao: 5.8, escalabilidade: 9.1 }
    },
    {
      id: "garrafa_motivacional_2l",
      title: "Garrafa Térmica Motivacional 2 Litros Squeeze com Canudo e Frases Marcadoras",
      livesCount: 52,
      rate: 26,
      sales: 4980,
      gmv: "R$ 149.400",
      category: "Utilidades & Esporte",
      competition: "Média",
      competitionColor: "#8e8e8e",
      margin: "R$ 1.150,00 / live",
      image: "https://s.500fd.com/tt_product/3e0f119bd363459386d988fd71cae4bb~tplv-aphluv4xwc-resize-jpeg:330:330.jpeg",
      salesToday: 135,
      salesYesterday: 140,
      weeklyGrowth: 15.4,
      creatorsCount: 52,
      commissionPercent: 15,
      commissionVal: 4.50,
      profitPotential: 22410.00,
      trendStatus: "estavel",
      scoreBreakdown: { demanda: 8.5, crescimento: 7.8, margem: 8.0, saturacao: 4.8, escalabilidade: 8.4 }
    },
    {
      id: "modelador_cabelo_airspin",
      title: "Modelador de Cabelo Cacheador Automático AirSpin Bivolt Cerâmica Turmalina",
      livesCount: 41,
      rate: 33,
      sales: 3290,
      gmv: "R$ 292.810",
      category: "Beleza & Cabelo",
      competition: "Baixa",
      competitionColor: "#5cc978",
      margin: "R$ 3.120,00 / live",
      image: "https://s.500fd.com/tt_product/78d55bd9b4bf43a4910a857206b59b98~tplv-aphluv4xwc-crop-webp:1024:1024.webp",
      salesToday: 112,
      salesYesterday: 98,
      weeklyGrowth: 45.0,
      creatorsCount: 41,
      commissionPercent: 20,
      commissionVal: 17.80,
      profitPotential: 58562.00,
      trendStatus: "alta",
      scoreBreakdown: { demanda: 9.1, crescimento: 9.7, margem: 9.6, saturacao: 3.2, escalabilidade: 9.4 }
    },
    {
      id: "cinta_masc",
      title: "Short Cinta Modeladora Masculina Bermuda de Compressão Plus Size Cueca Shapewear",
      livesCount: 57,
      rate: 23,
      sales: 4284,
      gmv: "R$ 149.510",
      category: "Roupas & Moda",
      competition: "Média",
      competitionColor: "#8e8e8e",
      margin: "R$ 1.526,72 / live",
      image: "https://s.500fd.com/tt_product/3e0f119bd363459386d988fd71cae4bb~tplv-aphluv4xwc-resize-jpeg:330:330.jpeg",
      salesToday: 184,
      salesYesterday: 142,
      weeklyGrowth: 29.5,
      creatorsCount: 57,
      commissionPercent: 15,
      commissionVal: 5.23,
      profitPotential: 22426.50,
      trendStatus: "alta",
      scoreBreakdown: { demanda: 8.8, crescimento: 9.2, margem: 8.0, saturacao: 4.5, escalabilidade: 8.9 }
    },
    {
      id: "kit_cilios_magneticos",
      title: "Kit 10 Pares Cílios Magnéticos Reutilizáveis com Delineador Magnético + Pinça",
      livesCount: 39,
      rate: 27,
      sales: 2950,
      gmv: "R$ 88.500",
      category: "Maquiagem & Beleza",
      competition: "Baixa",
      competitionColor: "#5cc978",
      margin: "R$ 980,00 / live",
      image: "https://s.500fd.com/tt_product/40644a40741b42b3a58af1e641612b3b~tplv-aphluv4xwc-resize-webp:800:800.webp",
      salesToday: 88,
      salesYesterday: 79,
      weeklyGrowth: 22.1,
      creatorsCount: 39,
      commissionPercent: 25,
      commissionVal: 7.50,
      profitPotential: 22125.00,
      trendStatus: "alta",
      scoreBreakdown: { demanda: 8.6, crescimento: 8.9, margem: 9.8, saturacao: 3.5, escalabilidade: 8.7 }
    },
    {
      id: "varal_retratil",
      title: "Varal Retrátil Dobrável de Parede em Aço Encapado Resistente 5 Metros",
      livesCount: 45,
      rate: 24,
      sales: 3557,
      gmv: "R$ 124.495",
      category: "Cozinha & Casa",
      competition: "Média",
      competitionColor: "#8e8e8e",
      margin: "R$ 1.310,00 / live",
      image: "https://s.500fd.com/tt_product/b5e487422d45496eaf883b32fafbe07b~tplv-aphluv4xwc-crop-webp:1500:1500.webp",
      salesToday: 110,
      salesYesterday: 95,
      weeklyGrowth: 18.2,
      creatorsCount: 45,
      commissionPercent: 15,
      commissionVal: 5.25,
      profitPotential: 18674.25,
      trendStatus: "estavel",
      scoreBreakdown: { demanda: 8.4, crescimento: 8.0, margem: 8.2, saturacao: 4.0, escalabilidade: 8.3 }
    },
    {
      id: "projetor_astronauta_led",
      title: "Luminária Projetor Galáxia Astronauta LED Bluetooth com Controle Remoto",
      livesCount: 68,
      rate: 30,
      sales: 5890,
      gmv: "R$ 412.300",
      category: "Eletrônicos & Casa",
      competition: "Alta",
      competitionColor: "#e0685f",
      margin: "R$ 2.450,00 / live",
      image: "https://s.500fd.com/tt_product/3e0f119bd363459386d988fd71cae4bb~tplv-aphluv4xwc-resize-jpeg:330:330.jpeg",
      salesToday: 185,
      salesYesterday: 170,
      weeklyGrowth: 27.8,
      creatorsCount: 68,
      commissionPercent: 16,
      commissionVal: 11.20,
      profitPotential: 65968.00,
      trendStatus: "alta",
      scoreBreakdown: { demanda: 9.3, crescimento: 8.8, margem: 8.9, saturacao: 5.5, escalabilidade: 9.0 }
    },
    {
      id: "maquininha_t9_barber",
      title: "Maquininha de Cortar Cabelo e Barba Vintage T9 Barber Sem Fio Recarregável",
      livesCount: 82,
      rate: 27,
      sales: 7120,
      gmv: "R$ 213.600",
      category: "Cuidados Pessoais",
      competition: "Média",
      competitionColor: "#8e8e8e",
      margin: "R$ 1.890,00 / live",
      image: "https://s.500fd.com/tt_product/40644a40741b42b3a58af1e641612b3b~tplv-aphluv4xwc-resize-webp:800:800.webp",
      salesToday: 210,
      salesYesterday: 195,
      weeklyGrowth: 21.4,
      creatorsCount: 82,
      commissionPercent: 18,
      commissionVal: 5.40,
      profitPotential: 38448.00,
      trendStatus: "estavel",
      scoreBreakdown: { demanda: 8.9, crescimento: 8.2, margem: 8.4, saturacao: 4.8, escalabilidade: 8.6 }
    },
    {
      id: "moedor_cafe",
      title: "Moedor de Grãos de Café Elétrico 110V-220v [Liquidação]",
      livesCount: 51,
      rate: 19,
      sales: 950,
      gmv: "R$ 20.896",
      category: "Eletrodomésticos",
      competition: "Alta",
      competitionColor: "#e0685f",
      margin: "R$ 510,80 / live",
      image: "https://s.500fd.com/tt_product/9a4ced0cc53a470eb2fdcf2328045029~tplv-o3syd03w52-crop-webp:1024:1024.webp",
      salesToday: 135,
      salesYesterday: 92,
      weeklyGrowth: 46.7,
      creatorsCount: 68,
      commissionPercent: 20,
      commissionVal: 12.99,
      profitPotential: 12340.50,
      trendStatus: "alta",
      scoreBreakdown: { demanda: 9.0, crescimento: 9.5, margem: 9.0, saturacao: 6.0, escalabilidade: 9.2 }
    },
    {
      id: "aparelho_kemei",
      title: "Aparelho de barbear 3 em 1 Kemei KM 6558 Recarregável Bivolt Preto",
      livesCount: 38,
      rate: 12,
      sales: 442,
      gmv: "R$ 16.277",
      category: "Beleza e cuidados pessoais",
      competition: "Alta",
      competitionColor: "#e0685f",
      margin: "R$ 380,45 / live",
      image: "https://s.500fd.com/tt_product/b1491f9f1624489aa564f56e7d5e2721~tplv-aphluv4xwc-resize-webp:800:800.webp",
      salesToday: 50,
      salesYesterday: 52,
      weeklyGrowth: -3.8,
      creatorsCount: 22,
      commissionPercent: 15,
      commissionVal: 7.49,
      profitPotential: 3310.58,
      trendStatus: "estavel",
      scoreBreakdown: { demanda: 7.2, crescimento: 6.0, margem: 7.5, saturacao: 5.8, escalabilidade: 7.0 }
    },
    {
      id: "sutia_canelado",
      title: "Kit Sutiã Canelado Confort Com Bojo Cores Premium",
      livesCount: 68,
      rate: 13,
      sales: 911,
      gmv: "R$ 15.225",
      category: "Roupas",
      competition: "Alta",
      competitionColor: "#e0685f",
      margin: "R$ 490,00 / live",
      image: "https://s.500fd.com/tt_product/13a02149f5c84d9a8216590a74f0c0f7~tplv-aphluv4xwc-crop-webp:1026:1024.webp",
      salesToday: 128,
      salesYesterday: 110,
      weeklyGrowth: 16.3,
      creatorsCount: 88,
      commissionPercent: 12,
      commissionVal: 3.59,
      profitPotential: 3270.49,
      trendStatus: "alta",
      scoreBreakdown: { demanda: 9.2, crescimento: 8.5, margem: 6.8, saturacao: 6.2, escalabilidade: 8.7 }
    },
    {
      id: "cinta_pala_dupla",
      title: "Kit Calcinhas Cinta Modeladora pala dupla imported!",
      livesCount: 57,
      rate: 10,
      sales: 573,
      gmv: "R$ 5.252",
      category: "Roupas",
      competition: "Alta",
      competitionColor: "#e0685f",
      margin: "R$ 210,00 / live",
      image: "https://s.500fd.com/tt_product/ecd4db78ecfc409594e03bc4c7bbb1fe~tplv-aphluv4xwc-resize-webp:330:330.webp",
      salesToday: 76,
      salesYesterday: 82,
      weeklyGrowth: -7.3,
      creatorsCount: 36,
      commissionPercent: 15,
      commissionVal: 4.19,
      profitPotential: 2400.87,
      trendStatus: "queda",
      scoreBreakdown: { demanda: 8.0, crescimento: 5.5, margem: 7.2, saturacao: 7.0, escalabilidade: 7.5 }
    },
    {
      id: "ventilador_teto",
      title: "Ventilador de Teto Lâmpada Controle Remoto Bivolt",
      livesCount: 77,
      rate: 6,
      sales: 441,
      gmv: "R$ 19.220",
      category: "Reformas residenciais",
      competition: "Alta",
      competitionColor: "#e0685f",
      margin: "R$ 380,00 / live",
      image: "https://s.500fd.com/tt_product/ee19f58380934f91920d137fe01a8da9~tplv-aphluv4xwc-resize-jpeg:330:330.jpeg",
      salesToday: 95,
      salesYesterday: 54,
      weeklyGrowth: 75.9,
      creatorsCount: 94,
      commissionPercent: 10,
      commissionVal: 19.22,
      profitPotential: 8476.02,
      trendStatus: "alta",
      scoreBreakdown: { demanda: 9.5, crescimento: 9.8, margem: 6.2, saturacao: 5.0, escalabilidade: 9.6 }
    }
  ],
  kpis: [
    { id: "receita_hoje", title: "Receita Hoje", value: "R$ 28.450,00", change: "+24.8%", positive: true, sparkline: [12, 18, 15, 24, 28, 35, 42, 48], icon: "💰", subtitle: "vs. ontem R$ 22.790" },
    { id: "receita_semana", title: "Receita Semana", value: "R$ 142.890,00", change: "+18.2%", positive: true, sparkline: [80, 95, 110, 105, 125, 138, 142], icon: "📈", subtitle: "vs. sem. anterior" },
    { id: "receita_mes", title: "Receita Mês", value: "R$ 512.400,00", change: "+31.5%", positive: true, sparkline: [300, 340, 380, 420, 470, 512], icon: "🏆", subtitle: "Meta: R$ 600K" },
    { id: "pedidos_totais", title: "Pedidos Totais", value: "1.842 un", change: "+14.2%", positive: true, sparkline: [120, 140, 135, 160, 175, 184], icon: "📦", subtitle: "Ticket Médio R$ 114,80" },
    { id: "produtos_ativos", title: "Produtos no Radar", value: "34 itens", change: "+4 novos", positive: true, sparkline: [20, 24, 25, 28, 30, 34], icon: "🔥", subtitle: "12 na sua Vitrine" },
    { id: "taxa_conversao", title: "Taxa de Conversão", value: "5.8%", change: "+1.2%", positive: true, sparkline: [3.8, 4.2, 4.5, 5.0, 5.4, 5.8], icon: "🎯", subtitle: "Média mercado: 3.2%" },
    { id: "tempo_live", title: "Tempo de Live Mês", value: "42h 15m", change: "+8h esta sem.", positive: true, sparkline: [15, 20, 28, 34, 38, 42], icon: "🎤", subtitle: "18 transmissões" },
    { id: "ctr_sacola", title: "CTR da Sacola", value: "9.4%", change: "+2.1%", positive: true, sparkline: [6.0, 6.8, 7.5, 8.2, 8.9, 9.4], icon: "🛍️", subtitle: "Clique no produto" },
    { id: "roas_medio", title: "ROAS Médio", value: "4.8x", change: "+0.6x", positive: true, sparkline: [3.2, 3.8, 4.0, 4.2, 4.5, 4.8], icon: "📊", subtitle: "Retorno de anúncios" },
    { id: "ticket_medio", title: "Ticket Médio", value: "R$ 114,80", change: "+5.4%", positive: true, sparkline: [98, 102, 105, 108, 112, 114], icon: "💳", subtitle: "Top: WePink Matte" },
    { id: "produtos_alta", title: "Produtos em Alta", value: "18 virais", change: "+6 hoje", positive: true, sparkline: [8, 10, 12, 14, 16, 18], icon: "🚀", subtitle: "Kalodata Sync" },
    { id: "lives_realizadas", title: "Lives Realizadas", value: "42 lives", change: "+12 este mês", positive: true, sparkline: [20, 25, 30, 35, 39, 42], icon: "⚡", subtitle: "Meta: 50 lives" }
  ],
  quickActions: [
    { id: "action_script", title: "Novo Script IA", desc: "Gerar roteiro com ganchos em 15s", icon: "✨", color: "#C8FF00", tab: "lives" },
    { id: "action_live", title: "Iniciar Nova Live", desc: "Abrir copiloto e teleprompter", icon: "🎤", color: "#FF6A00", tab: "lives-studio" },
    { id: "action_radar", title: "Radar de Produtos", desc: "Buscar produtos mais vendidos no TikTok", icon: "🔍", color: "#00E5FF", tab: "descobrir" },
    { id: "action_sync", title: "Sincronizar TikTok", desc: "Conectar sacola e dados reais", icon: "🔗", color: "#C8FF00", modal: "tiktok-sync" },
    { id: "action_samples", title: "Solicitar Amostra", desc: "Enviar mensagem IA ao vendedor", icon: "🎁", color: "#FF6A00", tab: "samples" },
    { id: "action_ai", title: "Diagnóstico da IA", desc: "Análise estratégica da sua conta", icon: "🧠", color: "#A855F7", tab: "ai-strategic" },
    { id: "action_extension", title: "Extensão Chrome OS", desc: "Automação da sacola ao vivo", icon: "🧩", color: "#00E5FF", tab: "extension" },
    { id: "action_analytics", title: "Analytics Avançado", desc: "ROAS, CPA e ROI detalhados", icon: "📊", color: "#C8FF00", tab: "analytics" },
    { id: "action_teleprompter", title: "Abrir Teleprompter", desc: "Painel de transmissão ao vivo", icon: "📜", color: "#FF6A00", tab: "lives" }
  ],
  aiFeed: [
    {
      id: "feed-1",
      type: "opportunity",
      title: "🔥 Oportunidade Urgente de Retenção",
      time: "Há 2 minutos",
      content: "Detectamos um pico de 2.450 pessoas na live no horário das 19h30. Recomendamos acionar o cupom de Frete Grátis e repetir o gancho de urgência nos próximos 60s.",
      badge: "ALTA CONVERSÃO",
      actionText: "Acionar Frete Grátis",
      actionTab: "lives-studio"
    },
    {
      id: "feed-2",
      type: "insight",
      title: "📈 Produto com Score 9.8 em Explosão",
      time: "Há 12 minutos",
      content: "O item 'Ventilador de Teto Lâmpada' teve um crescimento de +75.9% nas últimas 24h com GMV acumulado de R$ 19.220. Adicione-o à sua vitrine.",
      badge: "VIRAL TIKTOK",
      actionText: "+ Adicionar à Vitrine",
      productId: "ventilador_teto"
    },
    {
      id: "feed-3",
      type: "alert",
      title: "💡 Dica de Roteiro de Live",
      time: "Há 35 minutos",
      content: "Sua audiência costuma hesitar sobre a cobertura da Base WePink Matte. Mostre o teste de aplicação ao vivo no dorso da mão antes de chamar para a sacola.",
      badge: "QUEBRA DE OBJEÇÃO",
      actionText: "Ver Roteiro Recomendado",
      actionTab: "lives"
    }
  ],
  goals: [
    { id: "goal_vendas", title: "Meta de Faturamento Mensal", current: 512400, target: 600000, unit: "R$", color: "#C8FF00" },
    { id: "goal_lives", title: "Meta de Horas em Transmissão", current: 42, target: 50, unit: "horas", color: "#FF6A00" },
    { id: "goal_pedidos", title: "Meta de Pedidos no Mês", current: 1842, target: 2000, unit: "pedidos", color: "#00E5FF" },
    { id: "goal_conversao", title: "Meta de Taxa de Conversão", current: 5.8, target: 7.0, unit: "%", color: "#A855F7" }
  ],
  weeklyCalendar: [
    { id: "cal-1", day: "Hoje", time: "19:00", title: "Live Especial WePink Glow", product: "Base WePink Matte", status: "agendado" },
    { id: "cal-2", day: "Amanhã", time: "18:30", title: "Maratona Áudio & Games", product: "Fone Lenovo GM2 Pro", status: "agendado" },
    { id: "cal-3", day: "Sexta", time: "20:00", title: "Lançamento Skincare Noturno", product: "Sérum Retinol 0,3%", status: "confirmado" }
  ],
  notifications: [
    { id: "notif-1", title: "Novo Pedido de R$ 99,90", desc: "Comissão de R$ 19,98 creditada via Base WePink Matte", time: "Há 1 min", icon: "💰" },
    { id: "notif-2", title: "Amostra Grátis Aprovada!", desc: "A marca WePink Official aprovou seu envio de amostra", time: "Há 15 min", icon: "🎁" },
    { id: "notif-3", title: "Conexão SSE TikTok Ativa", desc: "Motor de dados em tempo real sincronizado com a API", time: "Há 1h", icon: "⚡" }
  ]
};

// Export dynamically for both Node and Browser envs
if (typeof module !== 'undefined' && module.exports) {
  module.exports = mockData;
} else {
  window.mockData = mockData;
}
